name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir build

      - name: Copy static files to build
        run: |
          cp index.html style.css build/
          
      - name: Inject Firebase Secrets and build app.js
        run: |
          # Replace the placeholders in app.js with the actual secrets
          sed -e "s|process.env.FIREBASE_API_KEY|'${{ secrets.FIREBASE_API_KEY }}'|" \
              -e "s|process.env.FIREBASE_AUTH_DOMAIN|'${{ secrets.FIREBASE_AUTH_DOMAIN }}'|" \
              -e "s|process.env.FIREBASE_PROJECT_ID|'${{ secrets.FIREBASE_PROJECT_ID }}'|" \
              -e "s|process.env.FIREBASE_STORAGE_BUCKET|'${{ secrets.FIREBASE_STORAGE_BUCKET }}'|" \
              -e "s|process.env.FIREBASE_MESSAGING_SENDER_ID|'${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'|" \
              -e "s|process.env.FIREBASE_APP_ID|'${{ secrets.FIREBASE_APP_ID }}'|" \
              app.js > build/app.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
